### ISSUE TITLE
Add CliFM

### ISSUE THREAD

**Issue by leo-arch** [agarrharr/awesome-cli-apps#491] opened 2021-12-06 13:59 UTC
[CliFM](https://github.com/leo-arch/clifm) is a file manager with a unique approach: unlike most terminal file managers out there, based on some kind of TUI, CliFM is entirely based on the command line.

**Comment by jneidel** [comment] 2021-12-06 16:47
duplicate of #486

**Closed by jneidel** 2021-12-06 16:47 UTC
